apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 67.7.0
    helm:
      releaseName: monitoring
      skipCrds: true
      values: |
        fullnameOverride: monitoring
        namespaceOverride: monitoring

        # On désactive les webhooks d'admission (évite le problème du secret manquant)
        admissionWebhooks:
          enabled: false

        grafana:
          enabled: true
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - grafana.ntl.mtk14m.com
            tls:
              - hosts:
                  - grafana.ntl.mtk14m.com
                secretName: grafana-tls

        prometheus:
          ingress:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true