apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/mtk14m/nautilius.git  
    targetRevision: main
    path: gitops/base/platform-api

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-services

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true